### ISSUE TITLE
bug：模型回答内容被截断，显示不全

### ISSUE THREAD

**Issue by qiufeihong2018** [KwokKwok/Silo#1]
复现截图 

![image](https://github.com/user-attachments/assets/c10b218e-f8a3-4b28-826d-9611ab371325)

**Comment by KwokKwok** [comment]
应该是 max_tokens 的问题，建议调整一下 max_tokens 到 4096 再尝试同样的问题

**Comment by KwokKwok** [comment]
<img width="523" alt="image" src="https://github.com/user-attachments/assets/9695e7b1-bd63-4b9a-b8b0-38ddfa955b96">
