### ISSUE TITLE
导入/导出功能

### ISSUE THREAD

**Issue by 228983380** [KwokKwok/Silo#13]
项目非常好，后期能否考虑增加如下功能

1、用户登录或者密码鉴权（环境变量设置也行）
2、数据库存储非Silo的其他ai的sk和模型路径，名称，接口地址等（环境变量设置也行）

方便个人在不同设备间不需要额外配置，直接使用。

**Comment by KwokKwok** [comment]
你好，纯前端的特性暂时不会改变，方便迁移、部署、学习。

针对你提出的问题，后续会开发 配置导入导出 功能。

**Comment by cr-zhichen** [comment]
> 你好，纯前端的特性暂时不会改变，方便迁移、部署、学习。
> 
> 针对你提出的问题，后续会开发 配置导入导出 功能。

密码鉴权的话，我有一个思路，是否可以通过配置对称加密的方式，在编译时对 key 进行加密，前端再使用秘钥进行解密，以实现类似密码鉴权的效果

**Comment by KwokKwok** [comment]
> 密码鉴权的话，我有一个思路，是否可以通过配置对称加密的方式，在编译时对 key 进行加密，前端再使用秘钥进行解密，以实现类似密码鉴权的效果

其实只要是前端直接请求大模型 API，控制台网络就可以直接看到携带的 key。单独前端加密可以认为是无意义的。

目前就是用户自己在弹框里填写密钥，是安全的。但是对于部署者来说，如果想提供体验密钥供用户打开网站不用输入密钥就能使用，就避免不了被恶意用户利用的可能。

**Comment by cr-zhichen** [comment]
> 其实只要是前端直接请求大模型 API，控制台网络就可以直接看到携带的 key。单独前端加密可以认为是无意义的。
> 
> 目前就是用户自己在弹框里填写密钥，是安全的。但是对于部署者来说，如果想提供体验密钥供用户打开网站不用输入密钥就能使用，就避免不了被恶意用户利用的可能。

我的意思是，秘钥本身是加密的，在请求前，根据用户在前端输入的“密码”将秘钥解密，然后在进行网络请求，这样其实在源码里是没有保存秘钥明文的

**Comment by KwokKwok** [comment]
> 我的意思是，秘钥本身是加密的，在请求前，根据用户在前端输入的“密码”将秘钥解密，然后在进行网络请求，这样其实在源码里是没有保存秘钥明文的

用户在弹框输入的密钥是不用这样做的，该密钥只会保存在本地。

如果你说的是部署者公开的体验密钥，代码现在不再保存密钥，已经去掉了，部署时会从环境变量读取。你这种做法是可以理解成增加恶意用户利用体验密钥的难度，但是不管怎么加密，只要打开控制台的网络，就能看到体验密钥
