### ISSUE TITLE
分享给朋友使用相关的密码保护功能

### ISSUE THREAD

**Issue by KwokKwok** [KwokKwok/Silo#16]
@cr-zhichen 提出的需求：想要分享给朋友，朋友直接可以使用。但是不想知道站点的人都可以直接使用

需要结合纯前端的特性，设计一下加密方法

如果以环境变量的方式把密码和密钥通过对称加密放在前端，因为前端代码的公开性（HTML），仍有被破解的风险

考虑的方案如下：
1. 增加一个 ‘分享给朋友’ 的按钮
2. 可选填写一个密码，将当前使用的密钥使用密码加密后，生成一个带加密后文字的链接
3. 朋友访问该链接，需要先输入密码，正确解密的密钥会存储在本地，相当于帮朋友填写密钥了

**Comment by cr-zhichen** [comment]
> 如果以环境变量的方式把密码和密钥通过对称加密放在前端，因为前端代码的公开性（HTML），仍有被破解的风险

将密码放入环境变量的方式，不会导致有被破解的风险，只需在NodeJs打包时，使用密码对秘钥进行加密，并只将加密后的秘钥写入构建产物中即可。

此时在构建产物中，没有密码和原始秘钥的存在，只有加密秘钥，只有在前端输入正确密码后，才能正确解密出秘钥。

-------

另外我还想到了一个简单的方法，直接在路由参数中接受秘钥明文实现秘钥输入，即可低成本快速的满足这样的需求

**Comment by KwokKwok** [comment]
> 将密码放入环境变量的方式，不会导致有被破解的风险，只需在NodeJs打包时，使用密码对秘钥进行加密，并只将加密后的秘钥写入构建产物中即可。

> 此时在构建产物中，没有密码和原始秘钥的存在，只有加密秘钥，只有在前端输入正确密码后，才能正确解密出秘钥。

没有原始密钥，怎么解密 -。-

**Comment by cr-zhichen** [comment]
> 没有原始密钥，怎么解密 -。-

有算法就能解密啊 不需要原始秘钥和密码

**Comment by KwokKwok** [comment]
> 有算法就能解密啊 不需要原始秘钥和密码

迷了，get 了，那就是 build 的时候执行一个脚本计算一下加密后的密钥，放到构建产物里
