### ISSUE TITLE
期待增加markdown解析功能

### ISSUE THREAD

**Issue by Pandolar** [KwokKwok/Silo#2]
你好博主，这是一个很不错的项目，非常感谢
但是我发现好像不会默认解析markdown的格式，如果有精力的话，建议增加对话的md格式解析

**Comment by KwokKwok** [comment]
<img width="1915" alt="image" src="https://github.com/user-attachments/assets/c1b946a3-b77c-4b4d-bc00-22afdcf5679e">

应该是有的，如果你的场景有问题，看是否有稳定复现步骤可提供

**Comment by Pandolar** [comment]
好的感谢，是我这边中转的问题，已经自行解决，叨扰了
