### ISSUE TITLE
feature request：希望可以增加一个按钮：一键清空所有消息，重新开始对话。（plus：非常好用的软件！！）

### ISSUE THREAD

**Issue by TTtrace** [KwokKwok/Silo#24]

**Comment by KwokKwok** [comment]
快捷支持清空所有对话。
<img width="843" alt="image" src="https://github.com/user-attachments/assets/285460b0-3eec-4eaa-b2bd-55e5880659f9">

应该一开始会有一个引导提到这一点，可能你没注意，点这里可以看到引导
<img width="648" alt="image" src="https://github.com/user-attachments/assets/7d1f2769-00ba-4534-a912-adb78e85dcdf">

**Comment by TTtrace** [comment]
原来如此，明白了！
