### ISSUE TITLE
能否支持带参数的调用

### ISSUE THREAD

**Issue by midpoint** [KwokKwok/Silo#27]
就是这样的格式： https://域名网址/#/chat?s=对话信息

这样就可以像搜索引擎一样调用。

谢谢！

**Comment by KwokKwok** [comment]
https://github.com/KwokKwok/Silo?tab=readme-ov-file#%E9%80%9A%E8%BF%87-url-%E8%AE%BE%E7%BD%AE%E5%8F%82%E6%95%B0
