### ISSUE TITLE
是否考虑增大输出Max token最大数值

### ISSUE THREAD

**Issue by xulei-shl** [KwokKwok/Silo#3]
版本：1.5.1

设置输出的 max token 最大为 4096。但插件已支持自定义模型，其中一些的最大输出 token 是超过 4096。希望可以支持设置更大的输出token

**Comment by KwokKwok** [comment]
现在直接输入不再设置限制。Web 端已更新，Chrome 扩展需要等下次提交版本更新
<img width="640" alt="image" src="https://github.com/user-attachments/assets/f1fa28ee-ecee-4334-b008-b3b42826bb77">
