### ISSUE TITLE
Retry Button Needed

### ISSUE THREAD

**Issue by cattail-mutt** [KwokKwok/Silo#30]
Could you please add a retry button? 
- When engaging in conversations with multiple models, output of gpt-4o often experiences interruptions, even if well below the max_token limit. A retry button within each conversation window would be a great solution.
- Additionally, the instability of upstream channel necessitates such a button to avoid the tedious "stop-clear-resend" process.

**Comment by KwokKwok** [comment]
Sounds great, maybe later, for now you can try this 
<img width="708" alt="image" src="https://github.com/user-attachments/assets/51172a77-5947-419f-abbe-af03c7b63f2f">

**Comment by KwokKwok** [comment]
this action will do "stop, remove last, resend last" now, try it
