### ISSUE TITLE
如何替换 硅基流动 的base url

### ISSUE THREAD

**Issue by midpoint** [KwokKwok/Silo#31]
有人架设了 [硅基流动公益api池](https://linux.do/t/topic/275566)
我想用这个公益服务，如何替换本服务的base url 呢？
谢谢！

**Comment by KwokKwok** [comment]
他的能查余额吗，不能的话，改了也用不了。

另外有个通用的方法，就是 自定义模型，OpenAI Compatible

<img width="763" alt="image" src="https://github.com/user-attachments/assets/70a65058-02e1-49d9-94f7-f19d84e673f0">
