### ISSUE TITLE
能否添加一个“场景”功能

### ISSUE THREAD

**Issue by midpoint** [KwokKwok/Silo#32]
意思就是相同功能的ai模型组合成一个场景，例如：
擅长文本的模型组合成 “秘书”；
擅长文本生成图的模型组合成 “神笔马良”；
擅长逻辑推理的模型组合成“福尔摩斯”；
擅长代码的组合成“资深码农”；
……
需要哪方面的信息，直接选择场景就可以调用合适的模型。

**Comment by KwokKwok** [comment]
https://github.com/user-attachments/assets/85f6c08d-0b45-4b94-8c47-6b76b036d70d

没有想到合适的处理方法，建议参考这个功能实现你的想法 [通过 URL 设置参数](https://github.com/KwokKwok/Silo?tab=readme-ov-file#%E9%80%9A%E8%BF%87-url-%E8%AE%BE%E7%BD%AE%E5%8F%82%E6%95%B0)
