### ISSUE TITLE
可以把聊天记录保存在本地吗？

### ISSUE THREAD

**Issue by jasper11452** [KwokKwok/Silo#33]
希望增加一个侧边栏，保存聊天记录到本地。
如果可以，希望能把配置文件也本地保存下。重装了一下chrome，密钥和prompt都没了。

**Comment by KwokKwok** [comment]
配置导出导入已经支持了，右上角-更多

**Comment by KwokKwok** [comment]
聊天记录这个问题，考虑到不同的对话可能使用不同模型、即使是相同模型可能使用不同参数，工作量可能比较大，目前考虑暂不做改动，望理解
