### ISSUE TITLE
“问问Silo”悬浮框

### ISSUE THREAD

**Issue by jasper11452** [KwokKwok/Silo#34]
右键菜单中的“问问silo”可不可以做成悬浮框样式啊？
可以参考https://github.com/josStorer/chatGPTBox ，他那个做的挺好，就是UI太丑了

**Comment by KwokKwok** [comment]
你是说选中之后，显示一个按钮吗？

**Comment by alexallen1** [comment]
@KwokKwok  
readme 里的ghcr.io/KwokKwok/silo:latest 

dont work:
ghcr.io/KwokKwok/silo:latest

worked:
ghcr.io/kwokkwok/silo:latest

还有个小问题：按shift+ins粘贴一大段代码进去时会有不会换行的bug

**Comment by KwokKwok** [comment]
@alexallen1 感谢反馈

> worked: ghcr.io/kwokkwok/silo:latest (README 已更新)
> 
> 按shift+ins粘贴一大段代码进去时会有不会换行的bug（改了一个可能相关的问题，可测试一下）

**Comment by jasper11452** [comment]
嗯...就是现在右键问问silo之后会占据整个页面，并且对话框在中间无法移动，想问下未来会有把它做成悬浮框的样子吗？或者集成到网页中？

**Comment by alexallen1** [comment]
@KwokKwok 小建议：加个restart: always
    image: ghcr.io/kwokkwok/silo:latest
    restart: always

**Comment by KwokKwok** [comment]
1. 现在顶栏支持拖动
2. 在**打开过**小助手之后，后续会有一个悬浮按钮支持点击唤起。（为了避免打扰，所以仅在通过右键唤起之后，才会显示该浮动按钮）

<img width="1503" alt="image" src="https://github.com/user-attachments/assets/52e1b5ba-3e8a-46bf-82a2-0bfb59548721" />
