### ISSUE TITLE
希望增加一个清除所有配置、恢复默认状态的按钮

### ISSUE THREAD

**Issue by SuiYunsy** [KwokKwok/Silo#35]

**Comment by KwokKwok** [comment]
你好，这个使用场景是什么呢？如果必要性不大，不希望增加按钮

目前可以通过以下方式达到目的：
1. 访问地址后加 `?clear` 会执行一次清空数据的操作（保留密钥），比如 `https://silo-chat.vercel.com?clear`，注意清空后，使用正常路径刷新页面即可
2. 因为项目数据都在浏览器端存储，可以清空站点数据（通过浏览器设置或者是控制台操作，主要存在 localStorage 中）

**Comment by SuiYunsy** [comment]
> 访问地址后加 `?clear` 会执行一次清空数据的操作

谢谢作者，有这个方式就方便多了~

---

目前程序有这样的逻辑：如果导出的配置中没有 chat_model_options 键，那么导入配置的时候就不会覆盖当前 localStorage 里已经设置的 chat_model_options 值。

所以我一开始觉得需要一个恢复默认状态的按钮，因为不知道哪些模型的哪些参数（maxToken、temp、topP等）被调整了。后面想想，改一个模型的参数再”应用到全部“其实也是可以的，问题解决。
