### ISSUE TITLE
无法粘贴内容

### ISSUE THREAD

**Issue by cm2457618290** [KwokKwok/Silo#36]
无法复制粘贴 只能打字，请问是我电脑问题吗

**Comment by KwokKwok** [comment]
谢谢反馈，这是前两天不小心改出来的 bug

**Comment by alexallen1** [comment]
@KwokKwok 2个小问题：
1：手机提问后 输出过程中状态，手机无法上滑看资料。等输出完 要一段时间。
2：[Silo]自定义请求地址填写http的地址/v1不能用，在nextchat填http的地址/v1能用；
[Silo]自定义请求地址 http套了https，能用了

**Comment by KwokKwok** [comment]
> @KwokKwok 2个小问题： 1：手机提问后 输出过程中状态，手机无法上滑看资料。等输出完 要一段时间。 2：[Silo]自定义请求地址填写http的地址/v1不能用，在nextchat填http的地址/v1能用； [Silo]自定义请求地址 http套了https，能用了

问题 1：今天会优化一下
问题 2： 因为浏览器限制，HTTPS 页面不能请求 http 资源，看是否 nextchat 是你本地启动的没有 https
