### ISSUE TITLE
能不能加上docker部署支持？

### ISSUE THREAD

**Issue by reccea** [KwokKwok/Silo#7]
这样会便方便

**Comment by KwokKwok** [comment]
个人不熟悉这种项目的 Docker 集成。我也会觉得 Docker 在这种场景过于重了些。纯前端的项目最好是打包为静态文件然后提供服务，可以是 Vercel、CDN、nginx 代理等方式。在这方面如有需要我可以提供相关协助。

如果仍对 Docker 集成需要，也欢迎大家参与贡献
